.Dd $Mdocdate: February 07 2024 $
.Dt VENUS 7
.Os
.Nm venus
.Nd A functional package manager
.Sh DESCRIPTION
The software venus is actually a set of tools that are used
together to power a
.Xr redo 1
scheme to manage packages in an
atomic and reproducible manner.
.Ss Store
The store is where the main scheme to manage the systems are,
it has the following directory hierarchy:
.Bl -tag -width modules
.It config
A directory where the configuration files are contained,
each file is encoded with
.Xr venus-conf 5
and declares the system's state of same name.
.It modules
A directory where each directory represents a module.
.It sys
A directory where each directory is a system with its state set by a config
file of same name.
.El
.Pp
It also has the following rules meant to use:
.Bl -tag -width modules
.It clean.do
A rule to clean all the cache.
.It sync.do
A rule to sync the all the systems states with their config file and collect
garbage.
.El
.Ss Modules
The modules are
.Xr redo 1
schemes to support repositories and packages format. Each module is mostly
free to set rules and its hierarchy according to its needs, the only rules
expected are:
.Bl -tag -width
.It cache/clean.do
A rule to clean the cache.
.It default.progs.do
A rule to create a directory populated with a sub-directory for each
package listed on
.Dq packages
at
.Dq ${module-name}
in the configuration file passed through the environmental variable
.Ev VENUS_CONFIG_FILE
encoded in
.Xr venus-conf 5 .
.El
.Sh SEE ALSO
.Xr venus-cksum 1 ,
.Xr venus-conf 1
