.Dd $Mdocdate: September 16 2024 $
.Dt venus-conf 1
.Os
.Sh NAME
.Nm venus-conf
.Nd retrieve values from venus-conf files
.Sh SYNOPSIS
.Nm
.Op Fl akltv
.Ar key
.Op Ar file
.Sh DESCRIPTION
The
.Nm
utility reads a
.Ar file ,
encoded in
.Xr venus-conf 5
format, and searches for the specified
.Ar key .
If found, it writes the corresponding value to standard output.
.Pp
If
.Ar key
is a single dash,
.Nm
treats the content itself a multi-value key.
.Pp
If
.Ar file
is a single dash
.Pq Sq \&-
or absent,
.Nm
reads from the standard input.
.Pp
By default, if no flag for key type is specified,
.Nm
searches for single-key keys.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Search for keys of any type.
.It Fl k
When processing multi-value keys, output only the keys.
.It Fl l
When processing multi-value keys, exclude values associated with keys.
.It Fl t
Search for multi-value keys only.
.It Fl v
When processing multi-value keys, output only the values.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr venus-conf 5
