.Dd $Mdocdate: February 07 2024 $
.Dt venus-conf 1
.Os
.Sh NAME
.Nm venus-conf
.Nd get keys from venus database files
.Sh SYNOPSIS
.Nm
.Op Fl t
.Ar key
.Op Ar file
.Sh DESCRIPTION
The
.Nm
utility reads a
.Ar file
and searches for the given
.Ar key
and, if found, write it to the standard output. The
.Ar file
must be encoded in
.Xr venus-conf 5
format.
.Pp
If
.Ar file
is a single dash
.Pq Sq \&-
or absent,
.Nm
reads from the standard input.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl l
List entries stripping the data associated with it.
.It Fl t
Search for multiple-value keys.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr venus-conf 5
