.Dd $Mdocdate: September 19 2021 $
.Dt VENUS-CHKSUM 5
.Os
.Sh NAME
.Nm venus-chksum
.Nd venus integrity file
.Sh DESCRIPTION
The
.Nm
file contains information to check each fetched package
integrity, as a list of name-checksum pairs. Each line has the format
.Ql <name>#<version>.v<extension>:checksum .
The checksum must be a valid Whirlpool message-digest
in hexadecimal format.
.Sh SEE ALSO
.Xr venus-cksum 1
.Xr venus-conf 1
