.Dd $Mdocdate: December 29 2019 $
.Dt VENUS-CKSUM 1
.Os
.Sh NAME
.Nm venus-cksum
.Nd write file checksums and sizes
.Sh SYNOPSIS
.Nm
.Op Fl w
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility writes to the standard output a single line for each
.Ar file ,
consiting of the path, the fletcher checksum and the number of octets.
If
.Ar file
is a single dash
.Pq Sq -
or absent,
.Nm
reads from the standard input.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl w
Set whirlpool as sum algorithm.
.El
.Sh EXIT STATUS
.Ex -std
