.Dd $Mdocdate: September 19 2021 $
.Dt VENUS-CFG 5
.Os
.Sh NAME
.Nm venus-cfg
.Nd venus configuration file
.Sh DESCRIPTION
The
.Nm
file contains configuration for
.Xr venus 1 .
The following variables are supported and obrigatory:
.Bl -tag -width uncompress
.It arch
Set the architecture of the system.
.It fetch
Set the tool used to fetch the packages.
.It root
Set the location where the packages are going to be installed.
.It safeurl
Set the main repository url.
.It uncompress
Set the tool used to uncompress the packages.
.It url
Set the packages repository.
.It safeurl
Set the security
.Pq dbfiles and chksum
repository.
.El
.Sh SEE ALSO
.Xr venus 1
.Xr venus-conf 1
