.Dd $Mdocdate: February 20 2025 $
.Dt venus-conf 1
.Os
.Sh NAME
.Nm venus-conf
.Nd retrieve values from venus-conf files
.Sh SYNOPSIS
.Nm
.Op Fl a | t
.Op Fl klqvx
.Ar key
.Op Ar file
.Sh DESCRIPTION
The
.Nm
utility reads a
.Ar file ,
encoded in
.Xr venus-conf 5
format, and searches for the specified
.Ar key .
If found, it writes the corresponding value to standard output.
.Pp
If
.Ar key
is a single dash,
.Nm
treats the content itself as a block. In this case, the order follows
the graph order, then the declaration order.
.Pp
If
.Ar file
is a single dash
.Pq Sq \&-
or absent,
.Nm
reads from the standard input.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Search for entries of any type.
.It Fl k
Filter for blocks and keys.
.It Fl l
Print blocks and keys as values
.Pq without its associated entries .
.It Fl t
Search for blocks only.
.It Fl v
Display only values for multi-value entries.
.It Fl x
Ignore commentaries. If specified twice ignore reference expansions.
.El
.Pp
If the options
.Fl a
and
.Fl t
are not specified, the default is to search only for key and value entries.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr venus-conf 5
